using EmployeeManager.Core.Models;
using EmployeeManager.Infrastructure.DataMocks;
using Microsoft.EntityFrameworkCore;

namespace EmployeeManager.Infrastructure;

public class AppDbContext:DbContext
{
    public AppDbContext(DbContextOptions<AppDbContext> options):base(options)
    {
        
    }

    //DbSet
    public DbSet<Employee> Employees { get; set; }
    public DbSet<Department> Departments { get; set; }

    //storing temporary department assignment
    public DbSet<EmployeeDepartmentAssignment> EmployeeDepartmentAssignments { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        modelBuilder.Entity<Department>(entity =>
        {
            entity.HasKey(d => d.Id);
            entity.Property(d => d.Name).IsRequired().HasMaxLength(100);

            entity.HasMany(d => d.Employees)
                .WithOne(e => e.Department)
                .HasForeignKey(e => e.DepartmentId)
                .OnDelete(DeleteBehavior.Restrict);
        });

        modelBuilder.Entity<Employee>(entity =>
        {
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Name).IsRequired().HasMaxLength(100);
            entity.Property(e => e.Email).IsRequired().HasMaxLength(100);
            entity.Property(e => e.DepartmentId);
        });

        // Configure temporary employee department assignments.
        modelBuilder.Entity<EmployeeDepartmentAssignment>(entity =>
        {
            // AssignmentId is the primary key and is generated by the database.
            entity.HasKey(a => a.AssignmentId);

            entity.Property(a => a.AssignmentId)
                .ValueGeneratedOnAdd();

            // AssignmentDate and Status are required.
            entity.Property(a => a.AssignmentDate)
                .IsRequired();

            entity.Property(a => a.Status)
                .IsRequired();

            // Each assignment belongs to one employee.
            entity.HasOne(a => a.Employee)
                .WithMany(e => e.DepartmentAssignments)
                .HasForeignKey(a => a.EmployeeId)
                .OnDelete(DeleteBehavior.Restrict);

            // Each assignment belongs to one department.
            entity.HasOne(a => a.Department)
                .WithMany(d => d.EmployeeAssignments)
                .HasForeignKey(a => a.DepartmentId)
                .OnDelete(DeleteBehavior.Restrict);
        });

        //Seed the database with mock data. HasData writes these rows into the
        //migration, so they are applied by "dotnet ef database update" (and by
        //Database.Migrate() in the integration tests) - there is no separate seeding step.
        modelBuilder.Entity<Department>().HasData(DepartmentDataMock.GetAllDepartments());
        modelBuilder.Entity<Employee>().HasData(EmployeeDataMock.GetAllEmployees());
    }
}